import {
  CREATE_ORDER,
  GET_ORDER_BY_ID,
  CREATE_PAYMENT,
  CREATE_PRODUCT,
  LIST_PRODUCTS,
  GET_PRODUCT_BY_ID,
  ADD_TO_WISHLIST,
  GET_CART_BY_USER_ID,
  ADD_TO_CART,
  UPDATE_CART_ITEM_QUANTITY,
  REMOVE_FROM_CART,
} from "../endpoints.js";

export default [
  CREATE_ORDER,
  GET_ORDER_BY_ID,
  CREATE_PAYMENT,
  CREATE_PRODUCT,
  LIST_PRODUCTS,
  GET_PRODUCT_BY_ID,
  ADD_TO_WISHLIST,
  GET_CART_BY_USER_ID,
  ADD_TO_CART,
  UPDATE_CART_ITEM_QUANTITY,
  REMOVE_FROM_CART,
];
