import {
  CREATE_ORDER,
  GET_ORDER_BY_ID,
  CREATE_PAYMENT,
  CREATE_PRODUCT,
  LIST_PRODUCTS,
  GET_PRODUCT_BY_ID,
  ADD_TO_WISHLIST,
} from "../endpoints.js";

export default [
  CREATE_ORDER,
  GET_ORDER_BY_ID,
  CREATE_PAYMENT,
  CREATE_PRODUCT,
  LIST_PRODUCTS,
  GET_PRODUCT_BY_ID,
  ADD_TO_WISHLIST,
];
