import {
  UPDATE_USER,
  DELETE_USER,
  CREATE_PRODUCT,
  UPLOAD_USER_IMAGE,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  LIST_PRODUCTS,
  GET_PRODUCT_BY_ID,
} from "../endpoints.js";

export default [
  UPDATE_USER,
  DELETE_USER,
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  UPLOAD_USER_IMAGE,
  DELETE_PRODUCT,
  LIST_PRODUCTS,
  GET_PRODUCT_BY_ID,
];
